### ISSUE TITLE
Iterate over rows (or columns) of a matrix

### ISSUE THREAD

**Issue by femtotrader** [JuliaCollections/IterTools.jl#11]
Hello,

following https://github.com/JuliaLang/julia/issues/14491
we should be able to iterate easily over columns (or over rows) of a matrix
but I'm not sure if this is in the scope of this package

Kind regards

**Comment by FelipeLema** [comment]
If anyone arrives here, this was added to Julia's Standard library in v1.1.0

https://github.com/JuliaLang/julia/pull/29749
