### ISSUE TITLE
imap doesn’t preserve type

### ISSUE THREAD

**Issue by scls19fr** [JuliaCollections/IterTools.jl#15]
Hello,

I don't really know if that a bug or a limitation but `imap` from [IterTools.jl](https://github.com/JuliaCollections/IterTools.jl) doesn't preserve type

```julia
julia> itr = imap(x->2*x, 1:10)
julia> collect(itr)
10-element Array{Any,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20
```

I was expecting same result (ie Vector of Int) as

```julia
julia> 2*collect(1:10)
10-element Array{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20
```

or

```julia
julia> map(x->2*x, 1:10)
10-element Array{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20
```

My goal is to simply apply a function to values of an iterator and get a new iterator (preserving type)

Kind regards

PS : crossposted on https://discourse.julialang.org/t/imap-from-itertools-jl-doesnt-preserve-type/7683

**Comment by iamed2** [comment]
The declaration `iteratoreltype(::Type{<:IMap}) = EltypeUnknown()` tells `collect` to try to figure out the type of the result itself. This has been fixed on `master` and produces the result you expected but unfortunately a release was never tagged! I'll do that now.

**Comment by scls19fr** [comment]
Thanks @iamed2
