### ISSUE TITLE
subsets() not working on Set() objects

### ISSUE THREAD

**Issue by roberthoenig** [JuliaCollections/IterTools.jl#27]
```julia
julia> for s in subsets(Set([1,2,3]))
           println(s)
       end
ERROR: MethodError: no method matching getindex(::Set{Int64}, ::Array{Bool,1})
Stacktrace:
 [1] next(::IterTools.Subsets{Set{Int64}}, ::Array{Bool,1}) at /home/robert/.julia/v0.6/IterTools/src/IterTools.jl:640
 [2] anonymous at ./<missing>:?
```

The docs say that `subsets` should work on collections. For me, it works for vectors, but not for sets. Am I doing something wrong?

**Comment by iamed2** [comment]
`subsets` currently requires collections be indexable; use `subsets(collect(my_set))` instead.

**Comment by roberthoenig** [comment]
If you want I can make a PR for either
* updating index.md to mentino that it only supports indexable collections
* modifying `subsets` to collect the set initially, if it's not an array,

**Comment by iamed2** [comment]
A PR for the former would be appreciated :) Could you also change the docstring in src/IterTools.jl?
