### ISSUE TITLE
New Iteration Protocol

### ISSUE THREAD

**Issue by iamed2** [JuliaCollections/IterTools.jl#34]
**Keno**:
> The recommendation is to either define iteration conditionally (if VERSION, then define one or the other) or just drop support for 0.6

I propose we have one file for 0.6 iterators and one for 0.7 iterators. I doubt there will be much shared code. Then once 1.0 is out we can just delete the 0.6 stuff.

I will probably start working on this soon so please post if you have any thoughts.

**Comment by ararslan** [comment]
Unless we're expecting any shiny new features or bugfixes to land that are relevant to 0.6, we could just go the way of FFTW and drop support for Julia < when the thing we need was merged.

**Comment by iamed2** [comment]
WIP at https://github.com/JuliaCollections/IterTools.jl/tree/ed/iterate
