### ISSUE TITLE
chain an iterator of iterators

### ISSUE THREAD

**Issue by Krastanov** [JuliaCollections/IterTools.jl#4]
Python's itertools has that - `chain.from_iterable`.

There was a pull request for Iterators.jl for that here: https://github.com/JuliaCollections/Iterators.jl/pull/34

It is useful for a couple of reasons:

- chain(xs...) splatting can be memory expensive
- chain(xs...) dispatch can be extremely slow (but it seems this is fixed now, given that `chain(xs...)=Chain(xs)` - either way, there is still unnecessary splatting)

Here are some timing results:

```
to_be_chained = (x:x+1000 for x in 1:1000)

# The current chain (splatting, but maybe? no slow dispatch)
@time collect(chain(to_be_chained...));
  4.676737 seconds (5.24 M allocations: 15.082 GiB, 41.03% gc time)

# Lazy chain implemented with a generator comprehension
@time collect((el for iter in to_be_chained for el in iter));
 0.141397 seconds (29.84 k allocations: 10.547 MiB, 3.31% gc time)
```

Naively I was thinking I can use `Chain` directly to skip the splatting, but `Chain` explicitly requires a `Tuple` of iterables, not a generic iterator of iterables:

```
@time collect(IterTools.Chain(to_be_chained))
MethodError: Cannot `convert` an object of type Base.Generator{UnitRange{Int64},##193#194} to an object of type IterTools.Chain
This may have arisen from a call to the constructor IterTools.Chain(...),
since type constructors fall back to convert methods.
```

**Comment by iamed2** [comment]
This exists in Base as `Iterators.flatten`

**Comment by Krastanov** [comment]
And just FYI, it is about even 10x faster than the "Lazy chain implemented with a generator comprehension" from my post above. Thanks for the pointer and sorry for not finding this!

**Comment by iamed2** [comment]
That's okay! It can be hard to find.
