### ISSUE TITLE
documentation please

### ISSUE THREAD

**Issue by schlichtanders** [JuliaCollections/IterTools.jl#50]
it would be awesome to have an updated documentation similar to the one in Iterators.jl

**Comment by iamed2** [comment]
There's a link in the README to https://juliacollections.github.io/IterTools.jl/stable

**Comment by schlichtanders** [comment]
I am so sorry, I haven't seen it.
This seems to be a new trend to refer documentation not by url but by fancy button.
People will get used to it probably

my excuses!

**Comment by iamed2** [comment]
It's okay! Yes it's common practice in Julia packages to rely on the badge rather than an explicit link.
