### ISSUE TITLE
Would takewhile be a natural candidate for IterTools.jl?

### ISSUE THREAD

**Issue by reinermartin** [JuliaCollections/IterTools.jl#51]
Would a takewhile function be a natural function to add to IterTools? It consumes a given iterator as long as a given condition is met.

So `collect(TakeWhile(Base.Iterators.countfrom(1), x-> x^2 <= 50))` would yield `[1, 2, 3, 4, 5, 6]`.

My own (simplistic?) implementation looks like this:

```
struct TakeWhile{I}
    xs::I
    cond::Function
end

Base.iterate(it::TakeWhile) = iterate(it.xs)

function Base.iterate(it::TakeWhile, state)
    (val, state) = iterate(it.xs, state)
    it.cond(state) || return nothing
    val, state
end

Base.IteratorSize(it::TakeWhile) = Base.SizeUnknown()
```

**Comment by iamed2** [comment]
Yes, although it could also be `takeuntil`

**Comment by reinermartin** [comment]
Sure; I was thinking of the Python module itertools, which provides `takeuntil()`. Best is to have both, as this is such a basic functional programming concept.

**Comment by iamed2** [comment]
Ah well we can choose the Python-similar one then :)

**Comment by ararslan** [comment]
FWIW `takewhile` is actually the standard name for this, and is provided in Scheme, C#, Haskell, Java, Kotlin, ...

**Comment by ararslan** [comment]
Your implementation looks good, I'd just swap the argument order to the constructor so that the function comes first, which is conventional.

**Comment by ararslan** [comment]
You can fork the package to your account by clicking "Fork" in the upper right corner of the page, next to "Star" and "Watch." You can then add add your fork as a [Git remote](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes), push your changes to your fork, then open a PR based on that.

**Comment by reinermartin** [comment]
Thanks ararslan, I'll try that now.

**Comment by reinermartin** [comment]
OK, I created a fork, added my code to three files mnaually, and created a pull request.

**Comment by reinermartin** [comment]
Oh, "All checks have failed" - would have been too easy... :-(

**Comment by reinermartin** [comment]
So I fixed (one) bug (copied one 'end' too many) - do I have to create new pull request, or what do I need to do?

**Comment by ararslan** [comment]
You can commit the changes to your branch then push to the remote again, which will automatically update the existing pull request.

**Comment by reinermartin** [comment]
If this works out I'll add 'takeuntil' some other day

**Comment by iamed2** [comment]
> If this works out I'll add 'takeuntil' some other day

Don't worry about it :)

**Comment by iamed2** [comment]
Added in https://github.com/JuliaCollections/IterTools.jl/pull/54

**Comment by ararslan** [comment]
> I have never contributed to any open source before.

Your first contribution was a great one!
