### ISSUE TITLE
Proposal: Add ShiftIterator to offset a given iterator with defined length

### ISSUE THREAD

**Issue by juliohm** [JuliaCollections/IterTools.jl#55]
Would you be interested in a PR with the iterator below? It accepts both positive as well as negative offsets:

```julia
struct ShiftIterator{I}
 itr::I
 offset::Int
 length::Int
 start::Int
end

function ShiftIterator(itr, offset)
 _, s = iterate(itr)
 start = s - 1
 len = length(itr)
 off = offset ≥ 0 ? offset : len + offset
 ShiftIterator{typeof(itr)}(itr, off, len, start)
end

function Base.iterate(itr::ShiftIterator, state=1)
 if state > itr.length
   nothing
 else
   s = ((state + itr.offset - 1) % itr.length) + itr.start
   item, _ = iterate(itr.itr, s)
   item, state + 1
 end
end

Base.length(itr::ShiftIterator) = itr.length
```

If yes, where should it go?

**Comment by iamed2** [comment]
So this is like a lazy rotation?

`start = s - 1` is a problem. Iterators do not have a known state type. 

Something like this is possible, for any iterator with at least `HasLength()`. But you need a version which doesn't depend on the iterator state being any particular value or type.

**Comment by juliohm** [comment]
Yes, lazy rotation. How would we make it work with any state type? In order words, how to "decrement" the state in a portable manner? I tried to generalize it but got busy with other tasks.

**Comment by ararslan** [comment]
See also https://github.com/piever/ShiftedArrays.jl

**Comment by juliohm** [comment]
Thanks for sharing, that package seems very useful for arrays :100: 

The `ShiftIterator` proposed here, however, is intended for general iterators with `HasLenght()`, and should theoretically be more lightweight.

**Comment by ararslan** [comment]
Right, that's why I say "see also" and not "this already exists" :wink:

**Comment by juliohm** [comment]
I don't know of any clean solution for it at the moment, I will just close the issue. Hope someone can tackle the problem in the future.
