### ISSUE TITLE
eager vs lazy evaluation

### ISSUE THREAD

**Issue by rapus95** [JuliaCollections/IterTools.jl#65]
Maybe we could begin unifying the iterator interface to a lazy only version to get people used to materializing manually where needed. Then we should add some Cache iterator and a materializing function though. The latter one would probably just call collect. The Cache iterator would be needed to prevent the [situation](https://github.com/JuliaLang/julia/issues/13712#issuecomment-150098428) that originally made Base use eager evaluation as the default.

**Comment by oxinabox** [comment]
Closed by #103  and just generally julia moving on
